# Build and Deploy to Azure

name: webstore-ci-cd

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'coolstore400'

jobs:
  build:
    name: 'Build and Publish .NET Web App'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2    

      - name: 'Restore'
        run: dotnet restore

      - name: 'Build'
        run: dotnet build --configuration Release

      - name: 'Publish'
        run: dotnet publish --configuration Release -o ./webstore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webstore
          path: ./webstore

  deploy: 
    name: Deploy to Web App
    runs-on: ubuntu-latest
    needs: build
    environment: 'production'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webstore

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
